### ISSUE TITLE
tag editor: can't save large files 

### ISSUE THREAD

**Issue by tbdal** [AdrienPoupa/VinylMusicPlayer#122]
Hey, 

Great player, great development! :)

One thing I encountered:
I'm not able to change the tag of large files definitely > 100MBs). The player will just close after some secs.

Can I do something about this / is the phone's memory too small / could you make this possible? 

I'm running LOS15.1 on a fp2.

Here is a log of the error:

FATAL EXCEPTION: AsyncTask #3
Process: com.poupa.vinylmusicplayer, PID: 7072
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 134217744 byte allocation with 25149440 free bytes and 126MB until OOM, max allowed footprint 94344688, growth limit 201326592
	at java.util.Arrays.copyOf(Arrays.java:3164)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at com.poupa.vinylmusicplayer.util.FileUtil.readBytes(Unknown Source:17)
	at com.poupa.vinylmusicplayer.util.SAFUtil.writeSAF(Unknown Source:158)
	at com.poupa.vinylmusicplayer.util.SAFUtil.write(Unknown Source:6)
	at com.poupa.vinylmusicplayer.ui.activities.tageditor.AbsTagEditorActivity$WriteTagsAsyncTask.doInBackground(Unknown Source:233)
	at com.poupa.vinylmusicplayer.ui.activities.tageditor.AbsTagEditorActivity$WriteTagsAsyncTask.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

**Comment by AdrienPoupa** [comment]
I just tried on a 650mb file without any issue. The trace you sent shows that you were writing to your sdcard. Can you reproduce it on your internal storage?

**Comment by tbdal** [comment]
Thanks for testing. I can't reproduce the error for files on the internal storage.
SD is still the same.

As a workaround copying the files back and forth works. 

One weird behaviour though: I can't navigate to: Folders - root - storage - emulated - 0 and therefore I can't navigate to the files. Is there any other way to get to the internal storage?

My workaround was the "last added" playlist

**Comment by AdrienPoupa** [comment]
Not sure there's anything we can do here, since it simply seems that your device does not have enough memory to write on the SDCard: https://stackoverflow.com/a/32245018/11989865
