### ISSUE TITLE
Version 0.21.0 crashes on Android 9

### ISSUE THREAD

**Issue by GermanGospel** [AdrienPoupa/VinylMusicPlayer#140]
0.21.0 does crash after finishing the welcome screens. The menu bar is shown for second and before any song is listed the app crashes on two Android 9 devices (Google Pixel 2 and Sony XZ1). The app runs normal on Android 7.1.2 (LOS14.1).

**Comment by paolovalerdi** [comment]
Try giving it permissions manually in settings

**Comment by AdrienPoupa** [comment]
Oh, you're right. It closes after the last screen, but if you reopen the application after that you see the prompt that you can access and the application loads normally.

**Comment by AdrienPoupa** [comment]
I reverted https://github.com/AdrienPoupa/VinylMusicPlayer/pull/121 and the bug is gone @soncaokim

**Comment by AdrienPoupa** [comment]
```
2019-04-13 11:37:02.284 3317-4044/? E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/audio/media/565640 from pid=2535, uid=10246 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:635)
        at com.android.providers.media.MediaProvider.enforceReadPermissionInner(MediaProvider.java:705)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:504)
        at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:495)
        at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:423)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:302)
        at android.os.Binder.execTransact(Binder.java:731)
2019-04-13 11:37:02.290 3317-1272/? E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/audio/media/565640 from pid=689, uid=1000 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:635)
        at com.android.providers.media.MediaProvider.enforceReadPermissionInner(MediaProvider.java:705)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:504)
        at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:495)
        at android.content.ContentProvider$Transport.openFile(ContentProvider.java:372)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:229)
        at android.os.Binder.execTransact(Binder.java:731)
2019-04-13 11:37:02.297 356-23869/? E/MediaPlayerService: Couldn't open fd for content://media/external/audio/media/565640
2019-04-13 11:37:02.297 2535-2679/com.poupa.vinylmusicplayer.debug E/MediaPlayerNative: Unable to create media player
2019-04-13 11:37:02.522 320-320/? E/WifiHAL: wifi_get_link_stats: requestResponse Error:-5
2019-04-13 11:37:02.523 689-1913/? E/WifiVendorHal: getWifiLinkLayerStats(l.937) failed {.code = ERROR_INVALID_ARGS, .description = }
2019-04-13 11:37:03.747 3317-1274/? E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/audio/media from pid=2535, uid=10246 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:635)
        at com.android.providers.media.MediaProvider.enforceReadPermissionInner(MediaProvider.java:705)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:504)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:215)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
        at android.os.Binder.execTransact(Binder.java:731)
2019-04-13 11:37:03.804 3317-4043/? E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/audio/media from pid=2535, uid=10246 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:635)
        at com.android.providers.media.MediaProvider.enforceReadPermissionInner(MediaProvider.java:705)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:504)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:215)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
        at android.os.Binder.execTransact(Binder.java:731)
    
    
    --------- beginning of crash
2019-04-13 11:37:03.806 2535-2704/com.poupa.vinylmusicplayer.debug E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
    Process: com.poupa.vinylmusicplayer.debug, PID: 2535
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
        at android.database.MergeCursor.<init>(MergeCursor.java:45)
        at com.poupa.vinylmusicplayer.loader.SongLoader.makeSongCursor(SongLoader.java:184)
        at com.poupa.vinylmusicplayer.loader.SongLoader.makeSongCursor(SongLoader.java:145)
        at com.poupa.vinylmusicplayer.loader.SongLoader.getAllSongs(SongLoader.java:43)
        at com.poupa.vinylmusicplayer.ui.fragments.mainactivity.library.pager.SongsFragment$AsyncSongLoader.loadInBackground(SongsFragment.java:152)
        at com.poupa.vinylmusicplayer.ui.fragments.mainactivity.library.pager.SongsFragment$AsyncSongLoader.loadInBackground(SongsFragment.java:145)
        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by AdrienPoupa** [comment]
@soncaokim https://github.com/AdrienPoupa/VinylMusicPlayer/commit/1c7e59e17cd1f7fb6a702374a956622b1d4ca26b this fixes it but I don't know if you need to ignore the exception or not

**Comment by GermanGospel** [comment]
@AdrienPoupa - The new Version does not fix the crashing on my two Android 9 devices! :-(

**Comment by AdrienPoupa** [comment]
I'm unable to reproduce it anymore on my 9 device so I'm going to need some logs.

To reproduce I did: delete cache and storage of the application to have a clean state, pass the introduction, allow permission

**Comment by AdrienPoupa** [comment]
Just tried a fresh install on a virtual Pixel 2, no crash

**Comment by GermanGospel** [comment]
@AdrienPoupa - A clean install from PlayStore did the job. Before I installed the same version via YalpStore. I never encountered a difference in the APKs provided by both!?

**Comment by AdrienPoupa** [comment]
Oh, I had no idea that the app was on Yalp... I have no clue how they build the application. It may have been an older version

**Comment by gkeegan** [comment]
Isn't Yalp just a different frontend for Google Play?

**Comment by AdrienPoupa** [comment]
Probably, I never used it myself. One thing is for sure though, I don't intend on supporting their apks

**Comment by gkeegan** [comment]
I believe it just gives the apks directly from Google Play, so that it isn't necessary to be signed in to a Google account, sort of like Apkmirror. It should be the same exact file as when you download off Google Play.

**Comment by AdrienPoupa** [comment]
If you want to avoid the Play Store, why would you use that when the application is available on fdroid?

**Comment by gkeegan** [comment]
No clue. I don't personally use Yalp.
