### ISSUE TITLE
Crash on launch on Android 11, Pixel 4a

### ISSUE THREAD

**Issue by nermolov** [AdrienPoupa/VinylMusicPlayer#288]
**Describe the bug**
App crashes upon launch. See logcat at end of issue.

**To Reproduce**
1. Launch application

**Expected behavior**
No crash.

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - Android Version: 11
 - ROM: Stock
 - Vinyl Music Player Version: ead7dd88 (F-Droid unisgned release build)

**Additional context**
Logcat:
```
09-12 16:48:28.007  1539  3703 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.poupa.vinylmusicplayer/.ui.activities.MainActivity bnds=[640,1315][841,1642]} from uid 10155
09-12 16:48:28.007  1539  1594 D EventSequenceValidator: Transition from ACTIVITY_CANCELLED to INTENT_STARTED
09-12 16:48:28.009 30281 31857 D CompatibilityChangeReporter: Compat change id reported: 150939131; UID 10164; state: DISABLED
09-12 16:48:28.020  1539  1594 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10300; state: DISABLED
09-12 16:48:28.020  1539  1594 D CompatibilityChangeReporter: Compat change id reported: 135754954; UID 10300; state: DISABLED
09-12 16:48:28.020  1539  1613 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10300; state: DISABLED
09-12 16:48:28.031  1539  1594 D EventSequenceValidator: Transition from INTENT_STARTED to ACTIVITY_LAUNCHED
09-12 16:48:28.031   856   856 D Zygote  : Forked child process 32094
09-12 16:48:28.035 32094 32094 I libc    : SetHeapTaggingLevel: tag level set to 0
09-12 16:48:28.038  1539  1613 I ActivityManager: Start proc 32094:com.poupa.vinylmusicplayer/u0a300 for pre-top-activity {com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.ui.activities.MainActivity}
09-12 16:48:28.045 32094 32094 E inylmusicplaye: Not starting debugger since process cannot load the jdwp agent.
09-12 16:48:28.046  2137  2137 W NgaMessageHandler: Invalid action "screen_state" for state:
09-12 16:48:28.046  2137  2137 W NgaMessageHandler:   NGA is Assistant = true
09-12 16:48:28.046  2137  2137 W NgaMessageHandler:   SysUI is NGA UI = true
09-12 16:48:28.059  1050  1050 I perfetto: ing_service_impl.cc:758 Configured tracing session 680, #sources:1, duration:5000 ms, #buffers:1, total buffer size:4096 KB, total sessions:1, uid:1071 session name: ""
09-12 16:48:28.059  1042  1042 I perfetto: probes_producer.cc:230  Ftrace setup (target_buf=680)
09-12 16:48:28.069  1042  1042 I perfetto: ftrace_procfs.cc:176    enabled ftrace
09-12 16:48:28.081 32094 32094 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
09-12 16:48:28.118 32094 32094 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-12 16:48:28.118 32094 32094 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-12 16:48:28.146   630  1728 W DisplayIdentification: Invalid EDID: falling back to serial number due to missing display name.
09-12 16:48:28.147   630  1728 W DisplayIdentification: Invalid EDID: falling back to ASCII text due to missing serial number.
09-12 16:48:28.186 17960 23548 I org.webrtc.Logging: EglRenderer: Duration: 4003 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
09-12 16:48:28.276 17960 23549 I org.webrtc.Logging: EglRenderer: Duration: 4002 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
09-12 16:48:28.340 32094 32094 W TabLayout: MODE_SCROLLABLE + GRAVITY_FILL is not supported, GRAVITY_START will be used instead
09-12 16:48:28.393 16341 16394 D AudioFlinger: ro.audio.silent is ignored since no output device is set
09-12 16:48:28.394 16341 16390 D AudioFlinger: ro.audio.silent is ignored since no output device is set
09-12 16:48:28.397  1539  4668 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
09-12 16:48:28.398  1539  3703 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
09-12 16:48:28.399  1539  3703 I chatty  : uid=1000(system) Binder:1539_18 identical 2 lines
09-12 16:48:28.400  1539  3703 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
09-12 16:48:28.400  1539  1568 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
09-12 16:48:28.401  2115  2115 V AvrcpMediaPlayerList: onActiveSessionsChanged: number of controllers: 0
09-12 16:48:28.401  1539  1568 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
09-12 16:48:28.401  1539  1568 I chatty  : uid=1000(system) Binder:1539_2 identical 1 line
09-12 16:48:28.402  1539  1568 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
09-12 16:48:28.403  1539  3703 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
09-12 16:48:28.404  2115  2115 V AvrcpMediaPlayerList: onActiveSessionsChanged: number of controllers: 1
09-12 16:48:28.405  2115  2115 D AvrcpMediaPlayerList: onActiveSessionsChanged: controller: com.poupa.vinylmusicplayer
09-12 16:48:28.406  2115  2115 D AvrcpMediaPlayerList: Already have a controller for the player: com.poupa.vinylmusicplayer, updating instead
09-12 16:48:28.488 32094 32121 I AdrenoGLES-0: QUALCOMM build                   : f84f8da, Ie73904e3bd
09-12 16:48:28.488 32094 32121 I AdrenoGLES-0: Build Date                       : 06/26/20
09-12 16:48:28.488 32094 32121 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.31.04.00
09-12 16:48:28.488 32094 32121 I AdrenoGLES-0: Local Branch                     : gfx-adreno.lnx.2.0
09-12 16:48:28.488 32094 32121 I AdrenoGLES-0: Remote Branch                    : quic/gfx-adreno.lnx.2.0
09-12 16:48:28.488 32094 32121 I AdrenoGLES-0: Remote Branch                    : NONE
09-12 16:48:28.488 32094 32121 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
09-12 16:48:28.488 32094 32121 I AdrenoGLES-0: Build Config                     : S P 10.0.4 AArch64
09-12 16:48:28.488 32094 32121 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
09-12 16:48:28.503  3569  3595 E SQLiteLog: (1) cannot modify audio_genres because it is a view in "DELETE FROM audio_genres WHERE (_id == 0)"
09-12 16:48:28.508  3569  3595 E DatabaseUtils: Writing exception to parcel
09-12 16:48:28.508  3569  3595 E DatabaseUtils: android.database.sqlite.SQLiteException: cannot modify audio_genres because it is a view (code 1 SQLITE_ERROR): , while compiling: DELETE FROM audio_genres WHERE (_id == 0)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1045)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:652)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at android.database.sqlite.SQLiteDatabase.validateSql(SQLiteDatabase.java:1944)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at com.android.providers.media.util.SQLiteQueryBuilder.delete(SQLiteQueryBuilder.java:734)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at com.android.providers.media.util.SQLiteQueryBuilder.lambda$delete$3(SQLiteQueryBuilder.java:691)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at com.android.providers.media.util.SQLiteQueryBuilder.lambda$delete$3$SQLiteQueryBuilder(Unknown Source:0)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at com.android.providers.media.util.-$$Lambda$SQLiteQueryBuilder$TqpmRZBeTEhfLyRQyEyDlFbBtxU.apply(Unknown Source:8)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at com.android.providers.media.DatabaseHelper.runWithTransaction(DatabaseHelper.java:555)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at com.android.providers.media.util.SQLiteQueryBuilder.delete(SQLiteQueryBuilder.java:690)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at com.android.providers.media.MediaProvider.lambda$deleteRecursive$17(MediaProvider.java:4421)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at com.android.providers.media.MediaProvider.lambda$deleteRecursive$17$MediaProvider(Unknown Source:0)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at com.android.providers.media.-$$Lambda$MediaProvider$66Co9d2SYurrd5nwUcTDCw0XWYU.apply(Unknown Source:13)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at com.android.providers.media.DatabaseHelper.runWithTransaction(DatabaseHelper.java:560)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at com.android.providers.media.MediaProvider.deleteRecursive(MediaProvider.java:4413)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at com.android.providers.media.MediaProvider.deleteInternal(MediaProvider.java:4383)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at com.android.providers.media.MediaProvider.delete(MediaProvider.java:4198)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at android.content.ContentProvider$Transport.delete(ContentProvider.java:435)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:214)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1154)
09-12 16:48:28.508  3569  3595 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1123)
09-12 16:48:28.509 32094 32132 W System.err: android.database.sqlite.SQLiteException: cannot modify audio_genres because it is a view (code 1 SQLITE_ERROR): , while compiling: DELETE FROM audio_genres WHERE (_id == 0)
09-12 16:48:28.510 32094 32132 W System.err: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:186)
09-12 16:48:28.510 32094 32132 W System.err: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
09-12 16:48:28.510 32094 32132 W System.err: 	at android.content.ContentProviderProxy.delete(ContentProviderNative.java:624)
09-12 16:48:28.510 32094 32132 W System.err: 	at android.content.ContentResolver.delete(ContentResolver.java:2289)
09-12 16:48:28.510 32094 32132 W System.err: 	at android.content.ContentResolver.delete(ContentResolver.java:2255)
09-12 16:48:28.510 32094 32132 W System.err: 	at com.poupa.vinylmusicplayer.loader.GenreLoader.getGenresFromCursor(Unknown Source:51)
09-12 16:48:28.510 32094 32132 W System.err: 	at com.poupa.vinylmusicplayer.loader.GenreLoader.getAllGenres(Unknown Source:4)
09-12 16:48:28.510 32094 32132 W System.err: 	at com.poupa.vinylmusicplayer.ui.fragments.mainactivity.library.pager.GenresFragment$AsyncGenreLoader.loadInBackground(Unknown Source:4)
09-12 16:48:28.510 32094 32132 W System.err: 	at com.poupa.vinylmusicplayer.ui.fragments.mainactivity.library.pager.GenresFragment$AsyncGenreLoader.loadInBackground(Unknown Source:0)
09-12 16:48:28.510 32094 32132 W System.err: 	at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(Unknown Source:0)
09-12 16:48:28.510 32094 32132 W System.err: 	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(Unknown Source:2)
09-12 16:48:28.510 32094 32132 W System.err: 	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(Unknown Source:2)
09-12 16:48:28.510 32094 32132 W System.err: 	at androidx.loader.content.ModernAsyncTask$2.call(Unknown Source:18)
09-12 16:48:28.510 32094 32132 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-12 16:48:28.510 32094 32132 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-12 16:48:28.510 32094 32132 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-12 16:48:28.510 32094 32132 W System.err: 	at java.lang.Thread.run(Thread.java:923)
09-12 16:48:28.517  3569  3595 E DatabaseUtils: Writing exception to parcel
09-12 16:48:28.517  3569  3595 E DatabaseUtils: java.lang.UnsupportedOperationException: Unknown or unsupported URL: content://media/external/audio/genres/-1798257890/members
09-12 16:48:28.517  3569  3595 E DatabaseUtils: 	at com.android.providers.media.MediaProvider.getQueryBuilderInternal(MediaProvider.java:4144)
09-12 16:48:28.517  3569  3595 E DatabaseUtils: 	at com.android.providers.media.MediaProvider.getQueryBuilder(MediaProvider.java:3617)
09-12 16:48:28.517  3569  3595 E DatabaseUtils: 	at com.android.providers.media.MediaProvider.queryInternal(MediaProvider.java:2196)
09-12 16:48:28.517  3569  3595 E DatabaseUtils: 	at com.android.providers.media.MediaProvider.query(MediaProvider.java:2146)
09-12 16:48:28.517  3569  3595 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:278)
09-12 16:48:28.517  3569  3595 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106)
09-12 16:48:28.517  3569  3595 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1154)
09-12 16:48:28.517  3569  3595 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1123)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #4
09-12 16:48:28.519 32094 32132 E AndroidRuntime: Process: com.poupa.vinylmusicplayer, PID: 32094
09-12 16:48:28.519 32094 32132 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at androidx.loader.content.ModernAsyncTask$3.done(Unknown Source:33)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: Unknown or unsupported URL: content://media/external/audio/genres/-1798257890/members
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:174)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1183)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1115)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1071)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.loader.GenreLoader.makeGenreSongCursor(Unknown Source:24)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.loader.GenreLoader.getSongs(Unknown Source:0)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.loader.GenreLoader.getGenreFromCursor(Unknown Source:10)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.loader.GenreLoader.getGenresFromCursor(Unknown Source:13)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.loader.GenreLoader.getAllGenres(Unknown Source:4)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.ui.fragments.mainactivity.library.pager.GenresFragment$AsyncGenreLoader.loadInBackground(Unknown Source:4)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.ui.fragments.mainactivity.library.pager.GenresFragment$AsyncGenreLoader.loadInBackground(Unknown Source:0)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(Unknown Source:0)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(Unknown Source:2)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(Unknown Source:2)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at androidx.loader.content.ModernAsyncTask$2.call(Unknown Source:18)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-12 16:48:28.519 32094 32132 E AndroidRuntime: 	... 3 more
09-12 16:48:28.522  1539 32136 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
09-12 16:48:28.524  1539  1567 W ActivityTaskManager:   Force finishing activity com.poupa.vinylmusicplayer/.ui.activities.MainActivity
09-12 16:48:28.527 32094 32121 I AdrenoGLES-0: PFP: 0x016ee189, ME: 0x00000000
09-12 16:48:28.547 32094 32121 W AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
09-12 16:48:28.547 32094 32121 W AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
09-12 16:48:28.553 31695 31730 I droid.apps.doc: Waiting for a blocking GC ProfileSaver
09-12 16:48:28.555  1539  1612 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
09-12 16:48:28.555  1539  1612 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
09-12 16:48:28.581 31695 31730 I droid.apps.doc: WaitForGcToComplete blocked ProfileSaver on ClassLinker for 27.835ms
09-12 16:48:28.581  1539  1594 D EventSequenceValidator: Transition from ACTIVITY_LAUNCHED to ACTIVITY_CANCELLED
```

**Comment by AdrienPoupa** [comment]
Works fine on Pixel 3 Android 11 emulator.

Related resource: https://stackoverflow.com/questions/59907819/error-getting-genre-columnsaudio-genres-in-android-q-android-10

**Comment by AdrienPoupa** [comment]
Can you try to install this experimental version and tell me if this is fixed? https://86-115534318-gh.circle-artifacts.com/0/outputs/circleci/release/app-circleci-release.apk

You may have to uninstall your current version and accept unsigned apps before installing it.

**Comment by nermolov** [comment]
@AdrienPoupa this did fix the crash on start issue, however I couldn't tap on anything but songs (tapping on albums or artists does nothing) and album art didn't show up.

However I'm downgrading to Android 10 at the moment as I'm sick of the bugs (namely stuttering music from any app while the screen is locked) so I won't be able to test further.

**Comment by AdrienPoupa** [comment]
Those may be different issues, unrelated to this one. Thank you!

**Comment by amrozinski** [comment]
@AdrienPoupa I had the crash issue on my Pixel 3XL after updating to Android 11. But I installed the experimental version you mentioned above and it worked. I had to uninstall the version I had on my phone first.

Quick question...will the experimental version update when you release future versions?

I love Vinyl by the way. Great alternative to Play Music, especially now that we're being forced to YouTube Music.

Thanks!

**Comment by AdrienPoupa** [comment]
@amrozinski thanks for the feedback! very informative.

Strange to see that you are not experiencing the bugs reported by @nermolov above?

I will soon release 0.24 that will include this fix, no worries

**Comment by AABatteries** [comment]
I can confirm the crash on startup issue on Pixel 3A running Android 11. I will test the fix provided here and report back.
I was super bummed seeing that the new system update broke my only music player

**Comment by ygsk10** [comment]
> Not reproduced Pixel 3 Android 11 emulator.
> 
> But other users reported it: [kabouzeid/Phonograph#849](https://github.com/kabouzeid/Phonograph/issues/849)

On AOSP on ARM64 (GSI) I loaded from DSU loader, there's no crash, yet no audio files appears in Vinyl, nor playable for opening from file manager.

**Comment by CrazyHairGuy** [comment]
I'm also experiencing what @nermolov was describing (the inability to interact with anything but songs and lack of album art) but also noticed the app crashes when tapping on a genre on a Pixel 2 running 11
