### ISSUE TITLE
IllegalStateException when opening

### ISSUE THREAD

**Issue by ByteHamster** [AdrienPoupa/VinylMusicPlayer#325]
**Describe the bug**
The app crashes directly after opening

**To Reproduce**
1. Open the app

**Expected behavior**
I can listen to music

**Screenshots**
None

**Smartphone (please complete the following information):**
 - Device: OnePlus 3T
 - Android Version: 10
 - ROM: LineageOS
 - Vinyl Music Player Version: 1.0.0 (F-Droid)

**Additional context**

```
10-19 08:41:02.067 25160 25195 I SQLiteConnectionPool: The connection pool for /data/user/0/com.poupa.vinylmusicplayer/databases/discography.db has been closed but there are still 1 connections in use.  They will be closed as they are released back to the pool.
10-19 08:41:02.068 25160 25192 W System.err: java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
10-19 08:41:02.068 25160 25192 W System.err: 	at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:1071)
10-19 08:41:02.069 25160 25192 W System.err: 	at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:763)
10-19 08:41:02.069 25160 25192 W System.err: 	at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:380)
10-19 08:41:02.069 25160 25192 W System.err: 	at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:896)
10-19 08:41:02.069 25160 25192 W System.err: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
10-19 08:41:02.069 25160 25192 W System.err: 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
10-19 08:41:02.069 25160 25192 W System.err: 	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
10-19 08:41:02.069 25160 25192 W System.err: 	at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1625)
10-19 08:41:02.070 25160 25192 W System.err: 	at com.poupa.vinylmusicplayer.discog.DB.removeSongById(Unknown Source:18)
10-19 08:41:02.070 25160 25192 W System.err: 	at com.poupa.vinylmusicplayer.discog.Discography.removeSongById(Unknown Source:7)
10-19 08:41:02.070 25160 25192 W System.err: 	at com.poupa.vinylmusicplayer.discog.Discography.getOrAddSong(Unknown Source:39)
10-19 08:41:02.070 25160 25192 W System.err: 	at com.poupa.vinylmusicplayer.loader.SongLoader.getSongFromCursorImpl(Unknown Source:76)
10-19 08:41:02.070 25160 25192 W System.err: 	at com.poupa.vinylmusicplayer.loader.SongLoader.getSongs(Unknown Source:13)
10-19 08:41:02.070 25160 25192 W System.err: 	at com.poupa.vinylmusicplayer.provider.MusicPlaybackQueueStore.getQueue(Unknown Source:15)
10-19 08:41:02.070 25160 25192 W System.err: 	at com.poupa.vinylmusicplayer.provider.MusicPlaybackQueueStore.getSavedPlayingQueue(Unknown Source:2)
10-19 08:41:02.070 25160 25192 W System.err: 	at com.poupa.vinylmusicplayer.service.MusicService.restoreQueuesAndPositionIfNecessary(Unknown Source:18)
10-19 08:41:02.070 25160 25192 W System.err: 	at com.poupa.vinylmusicplayer.service.PlaybackHandler.handleMessage(Unknown Source:28)
10-19 08:41:02.070 25160 25192 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:107)
10-19 08:41:02.070 25160 25192 W System.err: 	at android.os.Looper.loop(Looper.java:214)
10-19 08:41:02.071 25160 25192 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:67)
10-19 08:41:02.072 25160 25191 W System.err: java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
10-19 08:41:02.072 25160 25191 W System.err: 	at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:1071)
10-19 08:41:02.073 25160 25191 W System.err: 	at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:763)
10-19 08:41:02.073 25160 25191 W System.err: 	at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:380)
10-19 08:41:02.073 25160 25191 W System.err: 	at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:896)
10-19 08:41:02.073 25160 25191 W System.err: 	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
10-19 08:41:02.073 25160 25191 W System.err: 	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
10-19 08:41:02.073 25160 25191 W System.err: 	at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1627)
10-19 08:41:02.073 25160 25191 W System.err: 	at com.poupa.vinylmusicplayer.discog.DB.removeSongById(Unknown Source:18)
10-19 08:41:02.073 25160 25191 W System.err: 	at com.poupa.vinylmusicplayer.discog.Discography.removeSongById(Unknown Source:7)
10-19 08:41:02.073 25160 25191 W System.err: 	at com.poupa.vinylmusicplayer.discog.Discography.getOrAddSong(Unknown Source:39)
10-19 08:41:02.074 25160 25191 W System.err: 	at com.poupa.vinylmusicplayer.loader.SongLoader.getSongFromCursorImpl(Unknown Source:76)
10-19 08:41:02.074 25160 25191 W System.err: 	at com.poupa.vinylmusicplayer.loader.SongLoader.getSongs(Unknown Source:13)
10-19 08:41:02.074 25160 25191 W System.err: 	at com.poupa.vinylmusicplayer.loader.SongLoader.getAllSongs(Unknown Source:5)
10-19 08:41:02.074 25160 25191 W System.err: 	at com.poupa.vinylmusicplayer.discog.Discography.syncWithMediaStore(Unknown Source:8)
10-19 08:41:02.074 25160 25191 W System.err: 	at com.poupa.vinylmusicplayer.discog.Discography.access$100(Unknown Source:0)
10-19 08:41:02.074 25160 25191 W System.err: 	at com.poupa.vinylmusicplayer.discog.Discography$1.doInBackground(Unknown Source:11)
10-19 08:41:02.074 25160 25191 W System.err: 	at com.poupa.vinylmusicplayer.discog.Discography$1.doInBackground(Unknown Source:2)
10-19 08:41:02.151 25160 25191 W System.err: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
10-19 08:41:02.151 25160 25191 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-19 08:41:02.151 25160 25191 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
10-19 08:41:02.152 25160 25191 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-19 08:41:02.152 25160 25191 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-19 08:41:02.152 25160 25191 W System.err: 	at java.lang.Thread.run(Thread.java:919)
10-19 08:41:02.296 25160 25192 I SQLiteConnectionPool: The connection pool for /data/user/0/com.poupa.vinylmusicplayer/databases/discography.db has been closed but there are still 1 connections in use.  They will be closed as they are released back to the pool.
10-19 08:41:02.298 25160 25191 W System.err: java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
10-19 08:41:02.299 25160 25191 W System.err: 	at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:1071)
10-19 08:41:02.324  2546  4329 W ActivityTaskManager:   Force finishing activity com.poupa.vinylmusicplayer/.ui.activities.MainActivity
10-19 08:41:02.324 25160 25191 W System.err: 	at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:763)
10-19 08:41:02.325 25160 25191 W System.err: 	at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:380)
10-19 08:41:02.335  2546  5912 D OpenGLRenderer: endAllActiveAnimators on 0x7352d0d000 (RippleDrawable) with handle 0x739d066020
10-19 08:41:02.327 25160 25191 W System.err: 	at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:896)
10-19 08:41:02.348 25160 25191 W System.err: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
10-19 08:41:02.348 25160 25191 W System.err: 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
10-19 08:41:02.348 25160 25191 W System.err: 	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
10-19 08:41:02.348 25160 25191 W System.err: 	at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1625)
10-19 08:41:02.348 25160 25191 W System.err: 	at com.poupa.vinylmusicplayer.discog.DB.removeSongById(Unknown Source:18)
10-19 08:41:02.348 25160 25191 W System.err: 	at com.poupa.vinylmusicplayer.discog.Discography.removeSongById(Unknown Source:7)
10-19 08:41:02.349 25160 25191 W System.err: 	at com.poupa.vinylmusicplayer.discog.Discography.getOrAddSong(Unknown Source:39)
10-19 08:41:02.349 25160 25191 W System.err: 	at com.poupa.vinylmusicplayer.loader.SongLoader.getSongFromCursorImpl(Unknown Source:76)
10-19 08:41:02.349 25160 25191 W System.err: 	at com.poupa.vinylmusicplayer.loader.SongLoader.getSongs(Unknown Source:13)
10-19 08:41:02.349  2546  4329 I ActivityManager: Killing 25160:com.poupa.vinylmusicplayer/u0a135 (adj 905): crash
10-19 08:41:02.356  2546  4330 E InputDispatcher: Window handle Window{28618b8 u0 Application Error: com.poupa.vinylmusicplayer} has no registered input channel
10-19 08:41:02.377 25160 25191 W System.err: 	at com.poupa.vinylmusicplayer.loader.SongLoader.getAllSongs(Unknown Source:5)
10-19 08:41:02.377 25160 25191 W System.err: 	at com.poupa.vinylmusicplayer.discog.Discography.syncWithMediaStore(Unknown Source:8)
10-19 08:41:02.377  2546  4330 E InputDispatcher: Window handle Window{28618b8 u0 Application Error: com.poupa.vinylmusicplayer} has no registered input channel
10-19 08:41:02.426 12191 12191 W AvrcpMediaPlayerWrapper: The session was destroyed com.poupa.vinylmusicplayer
10-19 08:41:02.427 12191 12191 V AvrcpMediaPlayerList: onActiveSessionsChanged: number of controllers: 0
```

**Comment by ildar** [comment]
I've caught another IllegalStateException when Vinyl declined to play some
track (restarting the app fixes this). Logs show:

> 16548 16571 E AndroidRuntime: Process: com.poupa.vinylmusicplayer, PID:
16548
> 16548 16571 E AndroidRuntime: java.lang.IllegalStateException
> 16548 16571 E AndroidRuntime:        at
android.media.MediaPlayer.isPlaying(Native Method)
> 16548 16571 E AndroidRuntime:        at
com.poupa.vinylmusicplayer.service.MultiPlayer.isPlaying()
> 16548 16571 E AndroidRuntime:        at
com.poupa.vinylmusicplayer.service.MusicService.isPlaying()
> 16548 16571 E AndroidRuntime:        at
com.poupa.vinylmusicplayer.service.notification.PlayingNotificationImpl24.update()
> 16548 16571 E AndroidRuntime:        at
com.poupa.vinylmusicplayer.service.MusicService.updateNotification()
This is possibly the other bug. I'll file it later if it'll annoy me more.

**Comment by soncaokim** [comment]
On the first issue (reported by @ByteHamster) my guess is that there is some unsafe multithreading operation introduced by the recent change.

@ildar Please open another separate issue for the error you mentioned.
