### ISSUE TITLE
Artwork Editing causes crash

### ISSUE THREAD

**Issue by daemonspudguy** [AdrienPoupa/VinylMusicPlayer#437]
**Describe the bug**
When you try to add album artwork(at least to FLAC files), the app crashes

**To Reproduce**
1. Go to the tag editor for an album
2. Click on the artwork selector
3. Choose artwork

**Expected behavior**
The artwork to be added

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - Android Version: 11
 - ROM: stock
 - Vinyl Music Player Version: 1.2.0

**Additional context**
I have a logcat message here:

> FATAL EXCEPTION: AsyncTask #23
Process: com.poupa.vinylmusicplayer, PID: 12925
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/imageio/ImageIO;
	at org.jaudiotagger.tag.images.StandardArtwork.getImage(Unknown Source:9)
	at org.jaudiotagger.tag.images.StandardArtwork.setImageFromData(Unknown Source:0)
	at org.jaudiotagger.tag.flac.FlacTag.createField(Unknown Source:35)
	at org.jaudiotagger.tag.flac.FlacTag.setField(Unknown Source:0)
	at com.poupa.vinylmusicplayer.ui.activities.tageditor.AbsTagEditorActivity$WriteTagsAsyncTask.doInBackground(Unknown Source:328)
	at com.poupa.vinylmusicplayer.ui.activities.tageditor.AbsTagEditorActivity$WriteTagsAsyncTask.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
Caused by: java.lang.ClassNotFoundException: javax.imageio.ImageIO
	... 12 more

**Comment by soncaokim** [comment]
My guess: The `javax.imageio` is not shipped with Android (see https://stackoverflow.com/questions/16693011/cant-import-javax-imageio-imageio-in-android-application)

If this assumption is correct, this will not be solved anytime soon: the use of this desktop-only (i.e. non-Android) library is made inside the jaudiotagger lib -> problem needs to be fixed in that lib.

**Comment by AdrienPoupa** [comment]
I guess I need to update my jAudioTagger fork to fix this.

**Comment by soncaokim** [comment]
> I guess I need to update my jAudioTagger fork to fix this.

Nope, I've switched the fork to track a recent upstream commit already. I've briefly checked the issues on upstream, it has been discussed there with no resolution (cannot cite my sources now...)

**Comment by AJJLagerweij** [comment]
Is there an update on this? I run into this issue every once in a while.

**Comment by MintMain21** [comment]
Maybe this is related to https://github.com/AdrienPoupa/VinylMusicPlayer/issues/539 ?

**Comment by MintMain21** [comment]
No

**Comment by crunchymuffins** [comment]
This issue still exists unfortunately :'C
