### ISSUE TITLE
Samsung Voice Recorder m4a crashes app on details

### ISSUE THREAD

**Issue by Numerlor** [AdrienPoupa/VinylMusicPlayer#457]
**Describe the bug**
Going to the details popup through the file's three dot menu crashes the app for m4a files created by the Samsung Voice Recorder app

**To Reproduce**
1. Add the attached sample file to the app
2. Click on '⋮'
3. Click on 'Details'
4. Crash

**Expected behavior**
The Details popup should appear without the app crashing

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A71 SM-A715F/DS
 - Android Version: 11
 - ROM: Stock; One UI 3.1
 - Vinyl Music Player Version: 1.2.0

**Additional context**
The issue seems to occur because of lack of metadata, adding any metadata to the file through windows fixed the problem

[sample.zip](https://github.com/AdrienPoupa/VinylMusicPlayer/files/6577736/sample.zip)

**Comment by soncaokim** [comment]
Reproduced, for the record this is the crash (on an emulator)

```
    Process: com.poupa.vinylmusicplayer.ci.debug, PID: 5458
    org.jaudiotagger.audio.exceptions.NullBoxIdException: Unable to find next atom because identifier is invalid ��������
        at org.jaudiotagger.audio.mp4.atom.Mp4BoxHeader.update(Mp4BoxHeader.java:154)
        at org.jaudiotagger.audio.mp4.atom.Mp4BoxHeader.seekWithinLevel(Mp4BoxHeader.java:356)
        at org.jaudiotagger.audio.mp4.Mp4TagReader.read(Mp4TagReader.java:119)
        at org.jaudiotagger.audio.mp4.Mp4FileReader.getTag(Mp4FileReader.java:48)
        at org.jaudiotagger.audio.generic.AudioFileReader2.read(AudioFileReader2.java:61)
        at org.jaudiotagger.audio.AudioFileIO.readFile(AudioFileIO.java:357)
        at org.jaudiotagger.audio.AudioFileIO.read(AudioFileIO.java:193)
        at com.poupa.vinylmusicplayer.dialogs.SongDetailDialog.onCreateDialog(SongDetailDialog.java:96)
        at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:644)
        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:558)
        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1654)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
