### ISSUE TITLE
[BUG] NPE when app is closed

### ISSUE THREAD

**Issue by TacoTheDank** [AdrienPoupa/VinylMusicPlayer#469]
**Describe the bug**
App randomly crashes whenever it is closed.

**To Reproduce**
1. Open app
2. Start a song from the album tab and then stop it
3. Close app (by swiping away on window tabs)
4. Open app again
5. Close app again (!)

It is extremely sporadic; I can't seem to find a specific behavior or set of steps that causes it to occur consistently (sometimes the above doesn't even work), but it still happens about every 1/5 times. Also, this had happened on previous versions of the app. I just finally decided to report it lol.

**Expected behavior**
Uh, I guess not crash when I close the app.

**Smartphone (please complete the following information):**
 - Device: Samsung Note 9 (SM-N960U)
 - Android Version: 10
 - ROM: OneUI I guess, I don't use any custom firmware
 - Vinyl Music Player Version: 1.3.0 (build number 177)

**Additional context**
I can confirm this has nothing to do with the system killing the app for battery, as I've removed all restrictions on that front.
 
I've actually had two different crashes that look the same pertaining to this bug. I will post the crashlogs below.

```
FATAL EXCEPTION: main
Process: com.poupa.vinylmusicplayer, PID: 10505
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View com.poupa.vinylmusicplayer.ui.activities.base.AbsSlidingMusicPanelActivity.getSnackBarContainer()' on a null object reference
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.<init>(Unknown Source:11)
	at com.poupa.vinylmusicplayer.discog.Discography.triggerSyncWithMediaStore(Unknown Source:36)
	at b.b.a.d.c.run(:1)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

```
FATAL EXCEPTION: main
Process: com.poupa.vinylmusicplayer, PID: 14904
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Handler.removeCallbacksAndMessages(java.lang.Object)' on a null object reference
	at com.poupa.vinylmusicplayer.discog.Discography.triggerSyncWithMediaStore(Unknown Source:16)
	at b.b.a.d.c.run(:1)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

If you're wondering how I got these, I used my stacktrace-catching app called [Scoop](https://github.com/TacoTheDank/Scoop). Check it out! :)

**Comment by soncaokim** [comment]
Just wondering: you want to torture the app :-) or you have a reason to perform the sequence mentioned above?

And do you want to submit a patch for this?

**Comment by TacoTheDank** [comment]
There isn't really a reason to perform that specific sequence, it's just one way that I can get the crashes to at least sometimes occur; as noted, the crashes seem to be very sporadic and inconsistent, and different methods also make it crash sometimes as well. On the normal user end, they won't even know that the app has crashed (as the app has already been closed by that point). The only reason *I* know they occur is because my stacktrace-catching app catches them and notifies me.

I might submit a patch if I have the time, but my schedule is a bit inconsistent currently, so no guarantees. :)

**Comment by soncaokim** [comment]
I've attempted a fix with the linked PR.

**Comment by soncaokim** [comment]
Fixed by https://github.com/AdrienPoupa/VinylMusicPlayer/pull/470
