### ISSUE TITLE
NPE 

### ISSUE THREAD

**Issue by k3b** [AdrienPoupa/VinylMusicPlayer#472]
toaday i copied 159 new songs to sdcard of my phone. since then i cannot start the app anymore :-(.

The app now crashes with a NPE.

Before adding the new songs the app worked without issues.

I am not shure if one of the new songs is broken or if it is an issue with wrong character encoding in the meta data of one of the new songs.

here is the crash dump:

----------------------------------------------------------------

2021-06-26 18:08:47.169 14959-14989/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.poupa.vinylmusicplayer, PID: 14959
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
        at com.poupa.vinylmusicplayer.discog.tagging.MultiValuesTagUtil.splitImpl(Unknown Source:0)
        at com.poupa.vinylmusicplayer.discog.tagging.MultiValuesTagUtil.split(Unknown Source:2)
        at com.poupa.vinylmusicplayer.discog.MediaStoreBridge.getSongFromCursorImpl(Unknown Source:66)
        at com.poupa.vinylmusicplayer.discog.MediaStoreBridge.getSongs(Unknown Source:13)
        at com.poupa.vinylmusicplayer.discog.MediaStoreBridge.getAllSongs(Unknown Source:4)
        at com.poupa.vinylmusicplayer.discog.Discography.syncWithMediaStore(Unknown Source:27)
        at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(Unknown Source:21)
        at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(Unknown Source:2)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
2021-06-26 18:08:47.171 4197-4260/? I/[LGHome6]OverviewFlags: applyBackButtonAlpha(): alpha = 1,00, animate = true

----

I am using Vinyl 1.2.0 from f-drod on an android-10 LG-k10 phone.

The lg-k10 preinstalled music player and FooBar2000-music-player have no issues with the new songs

**Comment by soncaokim** [comment]
Are you able to start the app by removing the songs? I can have a look if you can isolate which song is causing the crash and uploading it for sample purpose.
