### ISSUE TITLE
Android 12 crash on foreground services call

### ISSUE THREAD

**Issue by Octoton** [AdrienPoupa/VinylMusicPlayer#557]
Now that the app is targeting android 12, and following some change in the foreground services authorization of android, the app will crash at any song transition (end of one song to the next) if run on an android 12 device and in the background.

Crash come from: _com.poupa.vinylmusicplayer.service.notification.PlayingNotification.updateNotifyModeAndPostNotification(PlayingNotification.java:58)_, I don't really understand the use of this part of the code and thus cannot go further at this time (@soncaokim, @AdrienPoupa do you have any idea of the use ?), however I can test any proposition.

This carsh is due to (https://developer.android.com/reference/android/app/Service#startForeground(int,%20android.app.Notification):
`Note: Beginning with SDK Version Build.VERSION_CODES.S, apps targeting SDK Version Build.VERSION_CODES.S or higher are not allowed to start foreground services from the background. See Behavior changes: Apps targeting Android 12 for more details. `
  
Full crash:
```
android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.poupa.vinylmusicplayer.ci.debug/com.poupa.vinylmusicplayer.service.MusicService
        at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
        at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
        at android.os.Parcel.readParcelable(Parcel.java:3333)
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2420)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7096)
        at android.app.Service.startForeground(Service.java:733)
        at com.poupa.vinylmusicplayer.service.notification.PlayingNotification.updateNotifyModeAndPostNotification(PlayingNotification.java:58)
        at com.poupa.vinylmusicplayer.service.notification.PlayingNotificationImpl24$1.update(PlayingNotificationImpl24.java:128)
        at com.poupa.vinylmusicplayer.service.notification.PlayingNotificationImpl24$1.onResourceReady(PlayingNotificationImpl24.java:82)
        at com.poupa.vinylmusicplayer.service.notification.PlayingNotificationImpl24$1.onResourceReady(PlayingNotificationImpl24.java:78)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:631)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:575)
        at com.bumptech.glide.load.engine.Engine.load(Engine.java:220)
        at com.bumptech.glide.request.SingleRequest.onSizeReady(SingleRequest.java:449)
        at com.poupa.vinylmusicplayer.glide.VinylSimpleTarget.getSize(VinylSimpleTarget.java:70)
        at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:251)
        at com.bumptech.glide.manager.RequestTracker.runRequest(RequestTracker.java:43)
        at com.bumptech.glide.RequestManager.track(RequestManager.java:674)
        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:641)
        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:608)
        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:599)
        at com.poupa.vinylmusicplayer.service.notification.PlayingNotificationImpl24.lambda$update$0$com-poupa-vinylmusicplayer-service-notification-PlayingNotificationImpl24(PlayingNotificationImpl24.java:78)
        at com.poupa.vinylmusicplayer.service.notification.PlayingNotificationImpl24$$ExternalSyntheticLambda0.run(Unknown Source:18)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1837)
        at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1350)
        at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:11903)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3205)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2498)
```

**Comment by soncaokim** [comment]
Hmm, nope.
Has `git blame` reveal anything (related commit, PR, etc)?

**Comment by Octoton** [comment]
Didn't had the time to look more into this, but will do

**Comment by soncaokim** [comment]
@Octoton  Can this be closed now?
